services:
  bot:
    build: 
      context: .
      dockerfile: bot.dockerfile
    env_file: ./bot/.env
    volumes:
      - ./bot/src:/app/src
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    env_file: ./backend/.env
    volumes:
      - ./backend/src:/app/src
    ports:
      - "3001:3001"
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    env_file: ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"